---
# tasks file for lighthouse-role
- name: Install Lighthouse
  hosts: lighthouse
  tasks:
    - name: Get lighthouse distrib
      ansible.builtin.get_url:
        url: "https://github.com/VKCOM/lighthouse/archive/refs/heads/master.zip"
        dest: /tmp/lighthouse.zip
        validate_certs: no
    - name: Add unzip
      yum:
        name: unzip
        state: present
      ignore_errors: "{{ ansible_check_mode }}"
      become: true
#    - name: create dir
#     ansible.builtin.file:
#        path: "/var/www"
#        state: directory
#        mode: '0755'
    - name: Add epel-release
      yum:
        name: epel-release
        state: present
      ignore_errors: "{{ ansible_check_mode }}"
      become: true
    - name: Install nginx
      yum:
        name: nginx
        state: present
      ignore_errors: "{{ ansible_check_mode }}"
      become: true
    - name: Unpack lighthouse
      ansible.builtin.unarchive:
        src: "/tmp/lighthouse.zip"
        dest: "/usr/share/nginx/html"
        remote_src: yes
      tags: lighthouse
      ignore_errors: "{{ ansible_check_mode }}"
      become: true
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/www
        state: directory
        recurse: yes
        owner: nginx
        group: nginx
        mode: '0644'
      become: true
    - name: Start nginx
      service:
        name: nginx
        state: started
      become: true
    - name: Stop Firewalld
      service:
        name: firewalld
        state: stopped
      become: true
      failed_when: false
